services:
  stable-diffusion-webui:
    container_name: "stable-diffusion-webui"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:7860
    volumes:
      - ./.data/outputs:/app/stable-diffusion-webui/outputs
      - ./.data/models:/app/stable-diffusion-webui/models
      - ./.data/extensions:/app/stable-diffusion-webui/extensions
      - ./.data/repositories:/app/stable-diffusion-webui/repositories
      - ./.data/cache:/root/.cache
    command: python launch.py --allow-code --listen --gradio-auth user:pass --api --administrator --disable-tls-verify --xformers --reinstall-xformers --theme=dark --no-prompt-history --enable-insecure-extension-access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]